controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    position_controller:
      type: position_controllers/JointGroupPositionController
    imu_sensor_broadcaster:
      type: imu_sensor_broadcaster/IMUSensorBroadcaster


velocity_controller:
  ros__parameters:
    joints:
      - Front_wheel_Joint
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
  
position_controller:
  ros__parameters:
    joints:
      - Front_Steering_Joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

imu_sensor_broadcaster:
  ros__parameters:
    sensor_name: IMU_Sensor
    frame_id: imu